-- WoDoom: DOOM E1M1 rendered from real WAD data (BSP, textures, sprites) as textured column strips.
-- Data and art are generated by tools/wad2wow.py.

local ADDON, ns = ...
local level, assets = ns.level, ns.assets

local floor, ceil, abs, sin, cos, sqrt, min, max, pi =
    math.floor, math.ceil, math.abs, math.sin, math.cos, math.sqrt, math.min, math.max, math.pi

-- Doom screen space is 320x200 with a 168-line 3D view; FX/FY scale it to frame pixels (4:3).
local SW, VIEWH, CX, CY = 320, 168, 160, 84
local SCALE = 160 -- projection scale for a 90 degree horizontal FOV
local COLS, COLW = 160, 2
local FX, FY = 2, 2.4
local FRAME_W, FRAME_H = SW * FX, 200 * FY
local TIC_RATE, TIC_TIME = 35, 1 / 35
local FAR, NEAR = 30000, 0.1

local EYE, RADIUS, STEP_H, BODY_H = 41, 16, 24, 56
local MAXMOVE, STOPSPEED, FRICTION = 30, 0x1000 / 65536, 0xe800 / 65536
local BAM = 4294967296
local USE_RANGE = 64

-- Doom's lighting: a sector's light level and the distance pick one of 32 colormaps; assets.cmap holds each map's RGB gain.
local Light = { gain = assets.cmap, extra = 0, chunk = 0, maxRegions = 5000 }
Light.presets = {
    dos = { cols = 320, chunk = 16, regions = 10000 }, -- full resolution, light varying across floor rows
    fast = { cols = 160, chunk = 0, regions = 5000 },
    hi = { cols = 320, chunk = 0, regions = 5000 },
}
Light.presets.lo = Light.presets.fast

function Light.pick(level)
    if level < 0 then level = 0 elseif level > 31 then level = 31 end
    return Light.gain[level + 1]
end

function Light.lightnum(li, contrast)
    local n = floor(li / 16) + Light.extra + (contrast or 0)
    if n < 0 then return 0 elseif n > 15 then return 15 end
    return n
end

-- Walls and sprites: the colormap index follows the scale, 2560 / depth (R_StoreWallRange and R_DrawVisSprite).
function Light.scaled(li, depth, contrast)
    local index = min(floor(2560 / depth), 47)
    return Light.pick((15 - Light.lightnum(li, contrast)) * 4 - floor(index / 2))
end

-- Floors and ceilings: the colormap index follows the distance along the ray (R_MapPlane).
function Light.span(li, distance)
    local j = min(floor(distance / 16), 127)
    return Light.pick((15 - Light.lightnum(li)) * 4 - floor(floor(160 / (j + 1)) / 2))
end

-- The weapon sprite uses the farthest scale step of its sector's light.
function Light.weapon(li)
    return Light.pick((15 - Light.lightnum(li)) * 4 - 23)
end

local TEX = "Interface\\AddOns\\" .. ADDON .. "\\tex\\"
local SPR = "Interface\\AddOns\\" .. ADDON .. "\\spr\\"
local FLAT = "Interface\\AddOns\\" .. ADDON .. "\\flat\\"

local sectors, segs, ssectors, nodes, lines =
    level.sectors, level.segs, level.ssectors, level.nodes, level.lines
local ROOT = level.root
local texInfo, sprInfo, flatInfo, thingSprite = assets.tex, assets.spr, assets.flats, assets.thing

-- Static data preparation ----------------------------------------------------------------------
for _, s in ipairs(segs) do s.len2 = s.len * s.len end
for name, info in pairs(texInfo) do
    info.key, info.path = "W" .. name, TEX .. name .. ".tga"
end
for name, info in pairs(sprInfo) do
    info.skey, info.hkey, info.path = "S" .. name, "H" .. name, SPR .. name .. ".tga"
    info.umax, info.vmax = info.w / info.pw, info.h / info.ph
end
local flatIdx, nFlat = {}, 0
for name, info in pairs(flatInfo) do
    nFlat = nFlat + 1
    flatIdx[name] = nFlat
    info.key, info.path = "P" .. name, FLAT .. name .. ".tga"
end
local gameTime, ticCount, updateAccumulator = 0, 0, 0
local ANIM_SEQ = { "NUKAGE1", "NUKAGE2", "NUKAGE3" }
local ANIM_POS = { NUKAGE1 = 0, NUKAGE2 = 1, NUKAGE3 = 2 }

local function currentFlat(name)
    local pos = ANIM_POS[name]
    if pos then return ANIM_SEQ[(pos + floor(gameTime * 35 / 8)) % 3 + 1] end
    return name
end

local ssSector = {}
for i, ss in ipairs(ssectors) do ssSector[i] = segs[ss.first].f end
for _, s in ipairs(sectors) do s.fl0, s.ce0, s.li0 = s.fl, s.ce, s.li end
for _, s in ipairs(segs) do s.mi0, s.up0, s.lo0 = s.mi, s.up, s.lo end
for _, L in ipairs(lines) do
    L.minx, L.maxx = min(L.x1, L.x2), max(L.x1, L.x2)
    L.miny, L.maxy = min(L.y1, L.y2), max(L.y1, L.y2)
end

-- BSP queries -------------------------------------------------------------------------------------
local function subsectorAt(x, y)
    local n = ROOT
    while n > 0 do
        local node = nodes[n]
        if node.dx * (y - node.y) - node.dy * (x - node.x) < 0 then n = node.r else n = node.l end
    end
    return -n
end

local function sectorAt(x, y)
    return ssSector[subsectorAt(x, y)]
end

-- Collision and line queries -------------------------------------------------------------------------
local function distToSeg2(px, py, x1, y1, x2, y2)
    local dx, dy = x2 - x1, y2 - y1
    local l2 = dx * dx + dy * dy
    local t = l2 > 0 and ((px - x1) * dx + (py - y1) * dy) / l2 or 0
    if t < 0 then t = 0 elseif t > 1 then t = 1 end
    local ex, ey = x1 + t * dx - px, y1 + t * dy - py
    return ex * ex + ey * ey
end

local function lineBlocksMove(L, curFloor)
    if L.bs == 0 or L.fl % 2 == 1 then return true end
    local F, B = sectors[L.fs], sectors[L.bs]
    local open = min(F.ce, B.ce) - max(F.fl, B.fl)
    return open < BODY_H or max(F.fl, B.fl) - curFloor > STEP_H
end

local solids, actors = {}, {}

local function canMove(x, y, curFloor, r)
    local r2 = r * r
    for i = 1, #lines do
        local L = lines[i]
        if x > L.minx - r and x < L.maxx + r and y > L.miny - r and y < L.maxy + r
            and distToSeg2(x, y, L.x1, L.y1, L.x2, L.y2) < r2 and lineBlocksMove(L, curFloor) then
            return false
        end
    end
    return true
end

local function blockedBySolid(x, y, r, self)
    for i = 1, #solids do
        local s = solids[i]
        if s ~= self and not s.gone then
            local dx, dy = s.x - x, s.y - y
            local rr = s.r + r
            if dx * dx + dy * dy < rr * rr then return true end
        end
    end
    for _, a in ipairs(actors) do
        if a ~= self and a.mon and a.hp > 0 then
            local dx, dy = a.x - x, a.y - y
            local rr = 20 + r
            if dx * dx + dy * dy < rr * rr then return true end
        end
    end
    return false
end

-- First blocking wall along a unit ray (closed doors and one-sided lines).
local function rayWall(px, py, dx, dy)
    local best = FAR
    for i = 1, #lines do
        local L = lines[i]
        local blocks = L.bs == 0
        if not blocks then
            local F, B = sectors[L.fs], sectors[L.bs]
            blocks = min(F.ce, B.ce) - max(F.fl, B.fl) <= 0
        end
        if blocks then
            local ex, ey = L.x2 - L.x1, L.y2 - L.y1
            local denom = dx * ey - dy * ex
            if abs(denom) > 1e-9 then
                local ax, ay = L.x1 - px, L.y1 - py
                local t = (ax * ey - ay * ex) / denom
                local s = (ax * dy - ay * dx) / denom
                if t > 0 and t < best and s >= 0 and s <= 1 then best = t end
            end
        end
    end
    return best
end

local function hasLOS(x1, y1, x2, y2)
    local dx, dy = x2 - x1, y2 - y1
    local d = sqrt(dx * dx + dy * dy)
    if d < 1 then return true end
    return rayWall(x1, y1, dx / d, dy / d) >= d
end

-- Game state --------------------------------------------------------------------------------------
-- Weapon animation states from Doom's info.c: { sprite, tics, action, flash }. The ready pose is `idle`.
-- Flash sequences are { sprite, tics, extra light } steps; the light drops back to 0 when one ends.
local WEAPONS = {
    { name = "FIST", idle = "PUNGA0", melee = true, sound = "DSPUNCH",
      attack = { { "PUNGA0", 5 }, { "PUNGB0", 4 }, { "PUNGC0", 4, "fire" }, { "PUNGD0", 5 }, { "PUNGC0", 4 },
          { "PUNGB0", 5, "refire" } } },
    { name = "PISTOL", idle = "PISGA0", pellets = 1, ammo = "bullets", sound = "DSPISTOL",
      attack = { { "PISGA0", 4 }, { "PISGB0", 6, "fire" }, { "PISGC0", 4 }, { "PISGB0", 5, "refire" } },
      flash = { { { "PISFA0", 7, 1 } } } },
    { name = "SHOTGUN", idle = "SHTGA0", pellets = 7, ammo = "shells", sound = "DSSHOTGN",
      attack = { { "SHTGA0", 3 }, { "SHTGA0", 7, "fire" }, { "SHTGB0", 5 }, { "SHTGC0", 5 }, { "SHTGD0", 4 },
          { "SHTGC0", 5 }, { "SHTGB0", 5 }, { "SHTGA0", 3 }, { "SHTGA0", 7, "refire" } },
      flash = { { { "SHTFA0", 4, 1 }, { "SHTFB0", 3, 2 } } } },
    { name = "CHAINGUN", idle = "CHGGA0", pellets = 1, ammo = "bullets", sound = "DSPISTOL",
      attack = { { "CHGGA0", 4, "fire", 1 }, { "CHGGB0", 4, "fire", 2 }, { "CHGGB0", 0, "refire" } },
      flash = { { { "CHGFA0", 5, 1 } }, { { "CHGFB0", 5, 2 } } } },
}

local MONSTERS = {
    [3004] = { prefix = "POSS", hp = 20, speed = 8, chaseTics = 4, painChance = 200, reaction = 8, drop = 2007,
        snd = { sight = { "DSPOSIT1", "DSPOSIT2", "DSPOSIT3" }, pain = "DSPOPAIN", active = "DSPOSACT",
            die = { "DSPODTH1", "DSPODTH2", "DSPODTH3" } },
        attack = { { "E", 10 }, { "F", 8 }, { "E", 8 } }, death = { "H", "I", "J", "K", "L" } },
    [9] = { prefix = "SPOS", hp = 30, speed = 8, chaseTics = 3, painChance = 170, reaction = 8, drop = 2001,
        snd = { sight = "DSSGTSIT", pain = "DSPOPAIN", active = "DSPOSACT", die = "DSSGTDTH" },
        attack = { { "E", 10 }, { "F", 10 }, { "E", 10 } }, death = { "H", "I", "J", "K", "L" } },
    [3001] = { prefix = "TROO", hp = 60, speed = 8, chaseTics = 3, painChance = 200, reaction = 8, melee = true,
        snd = { sight = { "DSBGSIT1", "DSBGSIT2" }, pain = "DSPOPAIN", active = "DSBGACT",
            die = { "DSBGDTH1", "DSBGDTH2" } },
        attack = { { "E", 8 }, { "F", 8 }, { "G", 6 } }, death = { "I", "J", "K", "L", "M" } },
}
local SOLID_RADIUS = { [2035] = 10, [2028] = 16, [48] = 16, [35] = 16 }
local SKIP_TYPES = { [1] = true, [2] = true, [3] = true, [4] = true, [11] = true }

-- Skill levels: thing-flag bit, ammo pickup multiplier, damage taken, and nightmare's faster monsters.
local SKILLS = {
    { lump = "M_JKILL", bit = 1, ammo = 2, hurt = 0.5 },
    { lump = "M_ROUGH", bit = 1, ammo = 1, hurt = 1 },
    { lump = "M_HURT", bit = 2, ammo = 1, hurt = 1 },
    { lump = "M_ULTRA", bit = 4, ammo = 1, hurt = 1 },
    { lump = "M_NMARE", bit = 4, ammo = 2, hurt = 1, fast = true },
}
local skill = 3
-- Title, skill menu and intermission state; its functions are defined near the end of the file.
local UI = { screen = "title", item = 3, t = 0, acc = 0, phase = 5, pause = 0, cnt = {}, kp = 0, ip = 0, sp = 0,
    seconds = 0, par = 30, back = "title", stack = {}, showMessages = true }

function SKILLS.monster(m)
    if not SKILLS[skill].fast then return m end
    local fast = {}
    for k, v in pairs(m) do fast[k] = v end
    fast.reaction, fast.chaseTics, fast.attack = 0, max(1, floor(m.chaseTics / 2)), {}
    for i, step in ipairs(m.attack) do fast.attack[i] = { step[1], max(1, floor(step[2] / 2)) } end
    return fast
end

local P = { x = 0, y = 0, momx = 0, momy = 0, angle = 0, turnheld = 0,
    viewheight = EYE, deltaviewheight = 0, floorZ = 0, bob = 0, viewbob = 0,
    wy = 0, wsx = 1, wsy = 32, wstate = "ready", refire = 0, faceCount = 0, attackDown = 0 }
local ang, hp, armor, bullets, shells, weapon, owned, kills, over
local viewz, floorZ = 0, 0
local hurt, faceT, faceFrame, msgT, nukeT = 0, 0, 0, 0, 0
local doors, floorMovers, lightEffects = {}, {}, {}
local doorTarget, secretSeen = {}, {}
local itemsFound, itemsTotal, killsTotal, secretsFound, secretsTotal = 0, 0, 0, 0, 0
local exitT, exitTime = 0, nil
local keys = {}
local msgText = ""

-- Doom's sound effects as OGG files (assets.snd). Sounds from a place in the world pick a volume and a
-- left/centre/right variant the way S_AdjustSoundParams does: full below 200 units, silent past 1200.
local Snd = { files = assets.snd or {}, last = {}, enabled = true, dir = "Interface\\AddOns\\" .. ADDON .. "\\snd\\" }

local function play(name, x, y)
    local kind = Snd.files[name]
    if not kind or not Snd.enabled then return end
    if UI.screen == "game" then
        if Snd.last[name] == ticCount then return end
        Snd.last[name] = ticCount
    end
    local file = name
    if x and kind == 2 then
        local dx, dy = x - P.x, y - P.y
        local dist = sqrt(dx * dx + dy * dy)
        if dist > 1200 then return end
        local side = sin((math.atan2 and math.atan2(dy, dx) or math.atan(dy, dx)) - ang)
        file = name .. "_" .. (dist < 450 and "a" or (dist < 800 and "b" or "c"))
            .. (side > 0.35 and "L" or (side < -0.35 and "R" or "C"))
    end
    PlaySoundFile(Snd.dir .. file .. ".ogg", "SFX")
end

-- Plays one of a monster's sounds (sight, pain, die, active); a list means pick one at random.
Snd.play = play

-- Music: PlayMusic loops the file until StopMusic. The track follows the screen (title, level, intermission).
Snd.music, Snd.musicOn, Snd.musicDir = assets.music or {}, true, "Interface\\AddOns\\" .. ADDON .. "\\music\\"

function Snd.stop()
    Snd.current = nil
    if StopMusic then StopMusic() end
end

function Snd.sync()
    local want = UI.screen == "inter" and "D_INTER" or (UI.back == "game" and "D_E1M1" or "D_INTRO")
    if not Snd.musicOn then want = nil end
    if want == Snd.current then return end
    Snd.stop()
    if want and Snd.music[want] and PlayMusic then
        PlayMusic(Snd.musicDir .. want .. ".ogg")
        Snd.current = want
    end
end

-- A monster's sounds: sight, pain, die or active; a list means pick one at random.
function Snd.mon(a, kind)
    local s = a.mon.snd and a.mon.snd[kind]
    if type(s) == "table" then s = s[random(#s)] end
    if s then play(s, a.x, a.y) end
end

local function setMessage(text)
    msgText, msgT = text, 140 -- HU_MSGTIMEOUT: four seconds
end

local function reset()
    for _, s in ipairs(sectors) do s.fl, s.ce, s.li = s.fl0, s.ce0, s.li0 end
    for _, s in ipairs(segs) do s.mi, s.up, s.lo = s.mi0, s.up0, s.lo0 end
    for _, L in ipairs(lines) do L.activated = nil end
    wipe(actors); wipe(doors); wipe(floorMovers); wipe(lightEffects); wipe(secretSeen); wipe(solids); wipe(doorTarget)
    for _, th in ipairs(level.things) do
        if th.t == 1 then
            P.x, P.y, ang = th.x, th.y, th.a * pi / 180
        elseif not SKIP_TYPES[th.t] and floor((th.f or 7) / SKILLS[skill].bit) % 2 == 1 then
            local a = { t = th.t, x = th.x, y = th.y, sprite = thingSprite[th.t], a = th.a * pi / 180 }
            local m = MONSTERS[th.t]
            m = m and SKILLS.monster(m)
            if m then
                a.mon, a.hp, a.cd, a.look = m, m.hp, 0, 0
                a.ambush = floor((th.f or 0) / 8) % 2 == 1
                a.frame, a.facing, a.walkT = "A", a.a, 0
                a.state, a.reactionT, a.moveCount = "idle", m.reaction, 0
            elseif SOLID_RADIUS[th.t] then
                a.r = SOLID_RADIUS[th.t]
                solids[#solids + 1] = a
                if th.t == 2035 then a.barrel, a.hp, a.frame, a.animT = true, 20, "A", 0 end
            end
            a.z = sectors[sectorAt(th.x, th.y)].fl
            if a.sprite then actors[#actors + 1] = a end
        end
    end
    hp, armor, bullets, shells, weapon, kills, over = 100, 0, 50, 0, 2, 0, nil
    P.armorType = 0
    P.wy, P.wsx, P.wsy, P.wstate, P.wi, P.fseq, P.pending = 0, 1, 32, "ready", nil, nil, nil
    P.refire, P.faceCount, P.attackDown, P.bonus, P.attX, P.attY = 0, 0, 0, 0, nil, nil
    UI.paused = false
    Light.extra = 0
    itemsFound, secretsFound, exitT, exitTime = 0, 0, 0, nil
    owned = { true, true }
    gameTime, ticCount = 0, 0
    updateAccumulator = 0
    hurt, nukeT, msgT, faceT = 0, 0, 0, 0
    P.momx, P.momy, P.turnheld = 0, 0, 0
    P.viewheight, P.deltaviewheight, P.bob, P.viewbob = EYE, 0, 0, 0
    P.angle = floor((ang % (2 * pi)) * BAM / (2 * pi))
    floorZ = sectors[sectorAt(P.x, P.y)].fl
    P.floorZ = floorZ
    viewz = floorZ + EYE
    for i, s in ipairs(sectors) do
        local minLight, maxLight, hasNeighbor = 255, 0, false
        for _, L in ipairs(lines) do
            if L.bs > 0 and (L.fs == i or L.bs == i) then
                local other = L.fs == i and L.bs or L.fs
                minLight = min(minLight, sectors[other].li0)
                maxLight = max(maxLight, sectors[other].li0)
                hasNeighbor = true
            end
        end
        if not hasNeighbor then minLight, maxLight = s.li0, s.li0 end
        local sp = s.sp
        if sp == 1 or sp == 2 or sp == 3 or sp == 4 or sp == 8 or sp == 12 or sp == 13 or sp == 17 then
            local e = { sec = i, min = minLight, max = s.li0, timer = 1, bright = true, dir = -1 }
            if sp == 1 then e.timer = random(1, 64)
            elseif sp == 2 or sp == 13 then e.timer = sp == 13 and 1 or random(1, 15)
            elseif sp == 3 or sp == 4 or sp == 12 then e.timer = sp == 12 and 1 or random(1, 35)
            elseif sp == 8 then e.min, e.max, e.timer = minLight, maxLight, 1
            elseif sp == 17 then e.timer, e.bright = 4, false end
            if sp == 17 then s.li = max(0, e.max - 16) end
            lightEffects[#lightEffects + 1] = e
        end
    end
end

-- Renderer: per-column BSP ray traversal ---------------------------------------------------------
local view = CreateFrame("Frame", "WoDoomFrame", UIParent)
view:SetSize(FRAME_W, FRAME_H)
view:SetPoint("CENTER")
view:SetFrameStrata("DIALOG")
view:SetClampedToScreen(true)
view:SetClipsChildren(true)
view:EnableKeyboard(true)
view:EnableMouse(true)
view:Hide()
tinsert(UISpecialFrames, "WoDoomFrame")

local backdrop = view:CreateTexture(nil, "BACKGROUND")
backdrop:SetAllPoints()
backdrop:SetColorTexture(0, 0, 0, 1)

-- Texture pools keyed by art, so each strip texture keeps the same image forever.
local pools = {}
local function acquire(key, path, layer, sub, wrap)
    local p = pools[key]
    if not p then
        p = { n = 0, last = 0 }
        pools[key] = p
    end
    local n = p.n + 1
    p.n = n
    local t = p[n]
    if not t then
        t = view:CreateTexture(nil, layer, nil, sub)
        if path then t:SetTexture(path, wrap or "CLAMP", wrap or "CLAMP", "NEAREST") else t:SetColorTexture(1, 1, 1, 1) end
        t.on = true
        p[n] = t
    elseif not t.on then
        t.on = true
        t:Show()
    end
    return t
end

local function releaseUnused()
    for _, p in pairs(pools) do
        for i = p.n + 1, p.last do
            local t = p[i]
            if t.on then
                t.on = false
                t:Hide()
            end
        end
        p.last, p.n = p.n, 0
    end
end

local Px, Py, Dx, Dy
local viewX, viewY
local top, bot, col, colDone
local zbuf = {}
local maskT = {} -- depth of a masked middle texture (a fence) in each column, for sprite layering
-- Per column, the open window (top/bottom) left after each portal, nearest first, for sprite clipping.
local MAXCLIP = 12
local clipN, clipT, clipTop, clipBot = {}, {}, {}, {}
-- Walls, floors and sprites are shaded by Light (defined near the top).
local function emitFlat(y0, y1, r, g, b)
    local Y0, Y1 = floor(y0 * FY + 0.5), floor(y1 * FY + 0.5)
    if Y1 <= Y0 then return end
    local t = acquire("F", nil, "ARTWORK", 0)
    t:SetPoint("TOPLEFT", col * COLW * FX, -Y0)
    t:SetSize(COLW * FX, Y1 - Y0)
    t:SetVertexColor(r, g, b)
end

local function emitSky(y0, y1)
    local Y0, Y1 = floor(y0 * FY + 0.5), floor(y1 * FY + 0.5)
    if Y1 <= Y0 then return end
    local info = texInfo.SKY1
    local t = acquire(info.key, info.path, "ARTWORK", 0, "REPEAT")
    local a = math.atan2 and math.atan2(Dy, Dx) or math.atan(Dy, Dx)
    local u0 = a / (2 * pi) * 4
    t:SetTexCoord(u0, u0 + (1.6 / 256) * COLW / 2, (y0 + 16) / 128, (y1 + 16) / 128)
    t:SetPoint("TOPLEFT", col * COLW * FX, -Y0)
    t:SetSize(COLW * FX, Y1 - Y0)
    t:SetVertexColor(1, 1, 1)
end

-- Floors and ceilings: each column marks the rows it shows of a plane (height, flat, light);
-- afterwards every row run becomes one quad whose texcoords follow the view rays.
local PLANE_CELLS = VIEWH * COLS
local rowPlane, planes, planeOf, nPlanes = {}, {}, {}, 0
for i = 1, PLANE_CELLS do rowPlane[i] = 0 end
local viewDirX, viewDirY, viewRX, viewRY = 1, 0, 0, -1
local function setColumnCount(n)
    if n ~= 160 and n ~= 320 then return false end
    if n ~= COLS then
        for i = 1, PLANE_CELLS do rowPlane[i] = nil end
        COLS, COLW = n, SW / n
        PLANE_CELLS = VIEWH * COLS
        for i = 1, PLANE_CELLS do rowPlane[i] = 0 end
    end
    return true
end

function Light.apply(preset)
    Light.chunk, Light.maxRegions = preset.chunk, preset.regions
    setColumnCount(preset.cols)
end

local function markPlane(h, flat, light, y0, y1)
    local key = ((flatIdx[flat] or 0) * 8192 + floor(h + 0.5) + 4096) * 256 + light
    local id = planeOf[key]
    if not id then
        nPlanes = nPlanes + 1
        id = nPlanes
        planeOf[key] = id
        local p = planes[id]
        if not p then
            p = {}
            planes[id] = p
        end
        p.h, p.flat, p.li = h, flat, light
    end
    local r0 = floor(y0)
    if r0 < 0 then r0 = 0 end
    local r1 = ceil(y1) - 1
    if r1 > VIEWH - 1 then r1 = VIEWH - 1 end
    local idx = col + 1 + r0 * COLS
    for _ = r0, r1 do
        rowPlane[idx] = id
        idx = idx + COLS
    end
end

local function emitPlaneRun(id, r, c0, c1)
    local p = planes[id]
    local dyT, dyB = r - CY, r + 1 - CY
    if dyT * dyB <= 0 then return end
    local info = flatInfo[currentFlat(p.flat)]
    if not info or not info.path then return end
    local dz = viewz - p.h
    local tT, tB, tC = dz * SCALE / dyT, dz * SCALE / dyB, dz * SCALE / (r + 0.5 - CY)
    local Y0, Y1 = floor(r * FY + 0.5), floor((r + 1) * FY + 0.5)
    -- dos preset: split the row so the light can change with distance across it.
    local chunk = Light.chunk > 0 and max(1, floor(Light.chunk / COLW)) or (c1 - c0 + 1)
    for a = c0, c1, chunk do
        local b = min(c1, a + chunk - 1)
        local xl, xr = (a * COLW - CX) / CX, ((b + 1) * COLW - CX) / CX
        local dxl, dyl = viewDirX + viewRX * xl, viewDirY + viewRY * xl
        local dxr, dyr = viewDirX + viewRX * xr, viewDirY + viewRY * xr
        local t = acquire(info.key, info.path, "ARTWORK", 0, "REPEAT")
        t:SetTexCoord((Px + dxl * tT) / 64, -(Py + dyl * tT) / 64, (Px + dxl * tB) / 64, -(Py + dyl * tB) / 64,
            (Px + dxr * tT) / 64, -(Py + dyr * tT) / 64, (Px + dxr * tB) / 64, -(Py + dyr * tB) / 64)
        t:SetPoint("TOPLEFT", a * COLW * FX, -Y0)
        t:SetSize((b - a + 1) * COLW * FX, Y1 - Y0)
        local xc = ((a + b + 1) * COLW / 2 - CX) / CX
        local g = Light.span(p.li, tC * sqrt(1 + xc * xc))
        t:SetVertexColor(g[1], g[2], g[3])
    end
end

local function flushPlanes()
    for r = 0, VIEWH - 1 do
        local base = r * COLS
        local c = 0
        while c < COLS do
            local id = rowPlane[base + c + 1]
            if id == 0 then
                c = c + 1
            else
                local c1 = c
                while c1 + 1 < COLS and rowPlane[base + c1 + 2] == id do c1 = c1 + 1 end
                emitPlaneRun(id, r, c, c1)
                c = c1 + 1
            end
        end
    end
end

local function emitWall(y0, y1, name, colU, texTopZ, k, g, sub)
    local Y0, Y1 = floor(y0 * FY + 0.5), floor(y1 * FY + 0.5)
    if Y1 <= Y0 then return end
    local info = texInfo[name]
    if not info then
        emitFlat(y0, y1, 0.3 * g[1], 0.3 * g[2], 0.3 * g[3])
        return
    end
    local z0, z1 = viewz + (CY - y0) / k, viewz + (CY - y1) / k
    local u0 = (floor(colU) % info.w) / info.w
    local t = acquire(info.key, info.path, "ARTWORK", sub or 1, "REPEAT")
    t:SetTexCoord(u0, u0 + 1 / info.w, (texTopZ - z0) / info.h, (texTopZ - z1) / info.h)
    t:SetPoint("TOPLEFT", col * COLW * FX, -Y0)
    t:SetSize(COLW * FX, Y1 - Y0)
    t:SetVertexColor(g[1], g[2], g[3])
end

local function texHeight(name)
    local info = texInfo[name]
    return info and info.h or 128
end

local function drawHit(s, t, u)
    local F = sectors[s.f]
    local B = s.b > 0 and sectors[s.b] or nil
    local k = SCALE / t
    local zc, zf = F.ce, F.fl
    local yc, yf = CY - (zc - viewz) * k, CY - (zf - viewz) * k
    local g = Light.scaled(F.li, t, s.dy == 0 and -1 or (s.dx == 0 and 1 or 0)) -- Doom's fake contrast
    local colU = s.xo + s.off + u * s.len + (s.sc and gameTime * 35 or 0)

    if yc > top then
        local y1 = min(yc, bot)
        if F.ct == "F_SKY1" then emitSky(top, y1) else markPlane(zc, F.ct, F.li, top, y1) end
    end
    if yf < bot then markPlane(zf, F.ft, F.li, max(yf, top), bot) end

    if not B then
        if s.mi then
            local topZ = (s.pb and (zf + texHeight(s.mi)) or zc) + s.yo
            emitWall(max(top, yc), min(bot, yf), s.mi, colU, topZ, k, g)
        end
        zbuf[col] = t
        colDone = true
        return
    end

    local zcb, zfb = B.ce, B.fl
    if F.ct == "F_SKY1" and B.ct == "F_SKY1" then zcb = zc end
    local ycb, yfb = CY - (zcb - viewz) * k, CY - (zfb - viewz) * k

    if zcb < zc and s.up then
        local topZ = (s.pt and zc or (zcb + texHeight(s.up))) + s.yo
        emitWall(max(top, yc), min(bot, ycb), s.up, colU, topZ, k, g)
    end
    if zfb > zf and s.lo then
        local topZ = (s.pb and zc or zfb) + s.yo
        emitWall(max(top, yfb), min(bot, yf), s.lo, colU, topZ, k, g)
    end
    if s.mi and texInfo[s.mi] then
        -- A masked texture (grate or fence) is drawn once, inside the opening, over a transparent background.
        local texH = texHeight(s.mi)
        local openTop, openBot = min(zc, zcb), max(zf, zfb)
        local topZ = (s.pb and (openBot + texH) or openTop) + s.yo
        local yTop, yBot = CY - (min(topZ, openTop) - viewz) * k, CY - (max(topZ - texH, openBot) - viewz) * k
        emitWall(max(top, yTop), min(bot, yBot), s.mi, colU, topZ, k, g, 3)
        maskT[col] = min(maskT[col] or FAR, t)
    end

    local nt, nb = max(yc, ycb), min(yf, yfb)
    if nt > top then top = nt end
    if nb < bot then bot = nb end
    local n = clipN[col]
    if n < MAXCLIP then
        n = n + 1
        clipN[col] = n
        local idx = col * MAXCLIP + n
        clipT[idx], clipTop[idx], clipBot[idx] = t, top, bot
    end    if top >= bot then
        zbuf[col] = t
        colDone = true
    end
end

local function processSub(id, t0, t1)
    local ss = ssectors[id]
    local best, bestT, bestU
    for k = ss.first, ss.first + ss.n - 1 do
        local s = segs[k]
        local denom = s.dx * Dy - s.dy * Dx
        if denom > 1e-9 then
            local t = -(s.dx * (Py - s.y1) - s.dy * (Px - s.x1)) / denom
            if t >= t0 - 0.01 and t <= t1 + 0.01 and t > NEAR and (not bestT or t < bestT) then
                local hx, hy = Px + t * Dx - s.x1, Py + t * Dy - s.y1
                local u = (hx * s.dx + hy * s.dy) / s.len2
                if u >= -0.001 and u <= 1.001 then
                    best, bestT, bestU = s, t, u
                end
            end
        end
    end
    if best then drawHit(best, bestT, bestU < 0 and 0 or (bestU > 1 and 1 or bestU)) end
end

local function traverse(n, t0, t1)
    if colDone then return end
    if n < 0 then return processSub(-n, t0, t1) end
    local node = nodes[n]
    local c0 = node.dx * (Py - node.y) - node.dy * (Px - node.x)
    local cd = node.dx * Dy - node.dy * Dx
    local sa = (c0 + cd * t0) < 0 and 0 or 1
    local sb = (c0 + cd * t1) < 0 and 0 or 1
    if sa == sb then
        return traverse(sa == 0 and node.r or node.l, t0, t1)
    end
    local t = -c0 / cd
    if t < t0 then t = t0 elseif t > t1 then t = t1 end
    local first, second
    if sa == 0 then first, second = node.r, node.l else first, second = node.l, node.r end
    traverse(first, t0, t)
    traverse(second, t, t1)
end

local function spriteEntry(a)
    if a.barrel then return (a.exploding and "BEXP" or "BAR1") .. a.frame .. "0", false end
    if not a.mon then return a.sprite end
    local typeFrames = assets.frames[a.mon.prefix]
    local frames = typeFrames and typeFrames[a.frame or "A"]
    if not frames then return a.sprite, false end
    local dx, dy = viewX - a.x, viewY - a.y
    local toViewer = math.atan2 and math.atan2(dy, dx) or math.atan(dy, dx)
    local rot = floor(((toViewer - (a.facing or a.a) + pi / 8) / (pi / 4))) % 8 + 1
    local entry = frames[rot] or frames[0] or frames[1]
    if entry then return entry.lump, entry.flip end
    return a.sprite, false
end

local function drawSprites(dirx, diry)
    local rightx, righty = diry, -dirx
    local list = {}
    for _, a in ipairs(actors) do
        local name, flip
        if a.gone then
            name = nil
        elseif a.mon then
            name, flip = spriteEntry(a)
        else
            name = spriteEntry(a)
        end
        if name and sprInfo[name] then
            local rx, ry = a.x - viewX, a.y - viewY
            local ty = rx * dirx + ry * diry
            if ty > 4 then
                a.sname, a.sflip, a.tx, a.ty = name, flip, rx * rightx + ry * righty, ty
                list[#list + 1] = a
            end
        end
    end
    table.sort(list, function(p, q) return p.ty > q.ty end)

    for _, a in ipairs(list) do
        local info = sprInfo[a.sname]
        local ty, k = a.ty, SCALE / a.ty
        local lo = a.sflip and info.w - info.lo or info.lo
        local x1 = CX + (a.tx - lo) * k
        local width = info.w * k
        local y1 = CY - (a.z + info.to - viewz) * k
        local height = info.h * k
        local Y0, Y1 = floor(y1 * FY + 0.5), floor((y1 + height) * FY + 0.5)
        if Y1 > Y0 then
            local bright = a.exploding or a.projectile or (a.fx and a.fx.bright and a.fxT < a.fx.tics)
            local g = bright and Light.gain[1] or Light.scaled(sectors[sectorAt(a.x, a.y)].li, ty)
            for c = max(0, floor(x1 / COLW)), min(COLS - 1, floor((x1 + width - 0.001) / COLW)) do
                if ty < zbuf[c] then
                    local u0 = max(0, (c * COLW - x1) / width)
                    local u1 = min(1, ((c + 1) * COLW - x1) / width)
                    if u1 > u0 then
                        local ctop, cbot = 0, VIEWH
                        local base = c * MAXCLIP
                        for j = 1, clipN[c] do
                            if clipT[base + j] >= ty then break end
                            ctop, cbot = clipTop[base + j], clipBot[base + j]
                        end
                        local ya, yb = max(y1, ctop), min(y1 + height, cbot)
                        local Ya, Yb = floor(ya * FY + 0.5), floor(yb * FY + 0.5)
                        if Yb > Ya then
                            local t = acquire(info.skey, info.path, "ARTWORK", maskT[c] and ty < maskT[c] and 4 or 2)
                            local uStart, uEnd = u0 * info.umax, u1 * info.umax
                            if a.sflip then uStart, uEnd = (1 - u0) * info.umax, (1 - u1) * info.umax end
                            t:SetTexCoord(uStart, uEnd, (ya - y1) / height * info.vmax, (yb - y1) / height * info.vmax)
                            t:SetPoint("TOPLEFT", c * COLW * FX, -Ya)
                            t:SetSize(COLW * FX, Yb - Ya)
                            t:SetVertexColor(g[1], g[2], g[3])
                        end
                    end
                end
            end
        end
    end
end

-- Draws a patch at Doom screen coordinates (320x200 space); gain tints it with a colormap.
local function drawPatch(name, x, y, layer, sub, gain)
    local info = sprInfo[name]
    if not info then return end
    local t = acquire(info.hkey, info.path, layer, sub)
    t:SetTexCoord(0, info.umax, 0, info.vmax)
    t:SetPoint("TOPLEFT", floor(x * FX + 0.5), -floor(y * FY + 0.5))
    t:SetSize(info.w * FX, info.h * FY)
    if gain then t:SetVertexColor(gain[1], gain[2], gain[3]) else t:SetVertexColor(1, 1, 1) end
end

local function drawNumber(value, rightX, y)
    local s = tostring(value)
    local x = rightX - 14 * #s
    for i = 1, #s do
        drawPatch("STTNUM" .. s:sub(i, i), x + 14 * (i - 1), y, "OVERLAY", 2)
    end
end

local function drawHud()
    drawPatch("STBAR", 0, 168, "OVERLAY", 1)
    local w = WEAPONS[weapon]
    if w.ammo then drawNumber(w.ammo == "bullets" and bullets or shells, 44, 171) end
    drawNumber(max(0, hp), 90, 171)
    drawPatch("STTPRCNT", 90, 171, "OVERLAY", 2)
    drawNumber(armor, 221, 171)
    drawPatch("STTPRCNT", 221, 171, "OVERLAY", 2)
    drawPatch(UI.face(), 143, 168, "OVERLAY", 2)
    drawPatch("STARMS", 104, 168, "OVERLAY", 2)
    for i = 0, 5 do
        local slot = i + 2
        drawPatch((owned[slot] and "STYSNUM" or "STGNUM") .. slot, 111 + (i % 3) * 12, 172 + floor(i / 3) * 10,
            "OVERLAY", 3)
    end
    local ammo = { { bullets, 200 }, { shells, 50 }, { 0, 50 }, { 0, 300 } }
    for i, row in ipairs(ammo) do
        UI.small(row[1], 288, 173 + (i - 1) * 6)
        UI.small(row[2], 314, 173 + (i - 1) * 6)
    end
end

local function drawWeapon()
    local w = WEAPONS[weapon]
    local name = P.wstate == "attack" and w.attack[P.wi][1] or w.idle
    local flash = P.fseq and P.fseq[P.fi][1]
    local lit = Light.weapon(sectors[sectorAt(P.x, P.y)].li)
    for i, n in ipairs({ name, flash }) do
        local info = sprInfo[n]
        if info then
            drawPatch(n, P.wsx - info.lo, 15.5 - info.to + P.wsy - 32, "OVERLAY", 0, i == 2 and Light.gain[1] or lit)
        end
    end
end

local function render()
    viewX, viewY = P.x, P.y
    Px, Py = P.x, P.y
    local dirx, diry = cos(ang), sin(ang)
    local rightx, righty = diry, -dirx
    viewDirX, viewDirY, viewRX, viewRY = dirx, diry, rightx, righty
    for i = 1, PLANE_CELLS do rowPlane[i] = 0 end
    wipe(planeOf)
    nPlanes = 0
    for i = 0, COLS - 1 do
        col = i
        local camX = (i * COLW + COLW * 0.5 - CX) / CX
        Dx, Dy = dirx + rightx * camX, diry + righty * camX
        top, bot, colDone = 0, VIEWH, false
        zbuf[i] = FAR
        clipN[i] = 0
        maskT[i] = nil
        traverse(ROOT, 0, FAR)
    end
    flushPlanes()
    drawSprites(dirx, diry)
    drawWeapon()
    drawHud()
    if msgT > 0 and (UI.showMessages or msgText == "Messages OFF") then UI.hu(msgText, 0, 0) end
    if UI.paused and sprInfo.M_PAUSE then drawPatch("M_PAUSE", (SW - sprInfo.M_PAUSE.w) / 2, 4, "OVERLAY", 3) end
    if UI.screen ~= "game" then UI.drawMenu() end
    releaseUnused()
    local shown = 0
    for _, p in pairs(pools) do shown = shown + p.last end
    if COLS == 320 and shown + 2 > Light.maxRegions then
        setColumnCount(160)
        Light.chunk, Light.maxRegions = 0, 5000
        if DEFAULT_CHAT_FRAME then DEFAULT_CHAT_FRAME:AddMessage("WoDoom: high-resolution view exceeded the texture limit; switched to 160 columns.") end
        render()
        return
    end
end

-- UI overlays -----------------------------------------------------------------------------------------
local hurtTex = view:CreateTexture(nil, "OVERLAY", nil, 4)
hurtTex:SetPoint("TOPLEFT")
hurtTex:SetSize(FRAME_W, FRAME_H)
hurtTex:SetColorTexture(1, 0, 0, 1)
hurtTex:SetAlpha(0)

-- Gameplay ------------------------------------------------------------------------------------------
-- Map mechanics live in one table to stay under Lua 5.1's limit of 200 locals.
local Mech = {}
Mech.centers = {}

-- World sounds for a sector come from the middle of its bounding box.
function Mech.sound(name, sec)
    local c = Mech.centers[sec]
    if not c then
        local x0, x1, y0, y1 = 1e9, -1e9, 1e9, -1e9
        for _, L in ipairs(lines) do
            if L.fs == sec or L.bs == sec then
                x0, x1, y0, y1 = min(x0, L.minx), max(x1, L.maxx), min(y0, L.miny), max(y1, L.maxy)
            end
        end
        c = { (x0 + x1) / 2, (y0 + y1) / 2 }
        Mech.centers[sec] = c
    end
    play(name, c[1], c[2])
end

function Mech.doorOpenHeight(sec)
    if doorTarget[sec] then return doorTarget[sec] end
    local low = 99999
    for _, L in ipairs(lines) do
        if L.bs > 0 and (L.fs == sec or L.bs == sec) then
            local other = L.fs == sec and L.bs or L.fs
            low = min(low, sectors[other].ce)
        end
    end
    doorTarget[sec] = low - 4
    return doorTarget[sec]
end

function Mech.openDoor(sec)
    for _, d in ipairs(doors) do
        if d.sec == sec then
            if d.state == "close" then d.state = "open"; Mech.sound("DSDOROPN", sec) end
            return
        end
    end
    doors[#doors + 1] = { sec = sec, state = "open", timer = 0 }
    Mech.sound("DSDOROPN", sec)
end

-- Monsters open ordinary doors (special 1) they bump into, like P_UseSpecialLine.
function Mech.monsterUse(a, x, y)
    for _, L in ipairs(lines) do
        if L.sp == 1 and floor(L.fl / 32) % 2 == 0
            and x > L.minx - 28 and x < L.maxx + 28 and y > L.miny - 28 and y < L.maxy + 28
            and distToSeg2(x, y, L.x1, L.y1, L.x2, L.y2) < 28 * 28
            and (L.x2 - L.x1) * (a.y - L.y1) - (L.y2 - L.y1) * (a.x - L.x1) < 0 then
            Mech.openDoor(L.bs)
            return true
        end
    end
    return false
end

function Mech.doorOccupied(sec)
    if sectorAt(P.x, P.y) == sec then return true end
    for _, a in ipairs(actors) do
        if a.mon and a.hp > 0 and sectorAt(a.x, a.y) == sec then return true end
    end
    return false
end

function Mech.updateDoors()
    for i = #doors, 1, -1 do
        local d = doors[i]
        local s = sectors[d.sec]
        if d.state == "open" then
            local target = Mech.doorOpenHeight(d.sec)
            s.ce = min(target, s.ce + 2)
            if s.ce >= target then d.state, d.timer = "wait", 150 end
        elseif d.state == "wait" then
            d.timer = d.timer - 1
            if d.timer <= 0 then d.state = "close"; Mech.sound("DSDORCLS", d.sec) end
        else
            local nextCe = max(s.ce0, s.ce - 2)
            if nextCe - s.fl < BODY_H and Mech.doorOccupied(d.sec) then
                d.state = "open"
                Mech.sound("DSDOROPN", d.sec)
            else
                s.ce = nextCe
            end
            if d.state == "close" and s.ce <= s.ce0 then
                table.remove(doors, i)
            end
        end
    end
end

function Mech.surroundingFloor(sec, highest)
    local current = sectors[sec].fl
    local result = highest and -99999 or current
    for _, L in ipairs(lines) do
        if L.bs > 0 and (L.fs == sec or L.bs == sec) then
            local other = L.fs == sec and L.bs or L.fs
            local height = sectors[other].fl
            if height < current then
                if highest then result = max(result, height) else result = min(result, height) end
            end
        end
    end
    return result
end

function Mech.activeFloorMover(sec)
    for _, mover in ipairs(floorMovers) do
        if mover.sec == sec then return true end
    end
    return false
end

function Mech.startFloorMotion(L)
    for i, s in ipairs(sectors) do
        if s.tg == L.tg and not Mech.activeFloorMover(i) then
            local neighbor = Mech.surroundingFloor(i, L.sp == 36)
            local target = L.sp == 36 and min(s.fl, neighbor + 8) or neighbor
            if target < s.fl then
                floorMovers[#floorMovers + 1] = {
                    sec = i, low = target, top = s.fl, state = "lower", timer = 0,
                }
                Mech.sound("DSPSTART", i)
            end
        end
    end
end

function Mech.floorMoveBlocked(sec, nextFloor)
    local s = sectors[sec]
    if nextFloor + BODY_H > s.ce then
        if sectorAt(P.x, P.y) == sec then return true end
        for _, a in ipairs(actors) do
            if a.mon and a.hp > 0 and sectorAt(a.x, a.y) == sec then return true end
        end
    end
    return false
end

function Mech.updateFloorMovers()
    for i = #floorMovers, 1, -1 do
        local mover = floorMovers[i]
        local s = sectors[mover.sec]
        if mover.state == "lower" then
            s.fl = max(mover.low, s.fl - 4)
            if ticCount % 8 == 0 then Mech.sound("DSSTNMOV", mover.sec) end
            if s.fl <= mover.low then
                mover.state, mover.timer = "wait", 105
                Mech.sound("DSPSTOP", mover.sec)
            end
        elseif mover.state == "wait" then
            mover.timer = mover.timer - 1
            if mover.timer <= 0 then
                mover.state = "raise"
                Mech.sound("DSPSTART", mover.sec)
            end
        else
            local nextFloor = min(mover.top, s.fl + 4)
            if Mech.floorMoveBlocked(mover.sec, nextFloor) then
                mover.state = "lower"
            else
                s.fl = nextFloor
                if ticCount % 8 == 0 then Mech.sound("DSSTNMOV", mover.sec) end
                if s.fl >= mover.top then
                    table.remove(floorMovers, i)
                    Mech.sound("DSPSTOP", mover.sec)
                end
            end
        end
    end
    floorZ, P.floorZ = sectors[sectorAt(P.x, P.y)].fl, sectors[sectorAt(P.x, P.y)].fl
    viewz = floorZ + P.viewheight + P.viewbob
    for _, a in ipairs(actors) do
        if not a.projectile then a.z = sectors[sectorAt(a.x, a.y)].fl end
    end
end

function Mech.updateLightEffects()
    for _, e in ipairs(lightEffects) do
        local s = sectors[e.sec]
        local sp = s.sp
        if sp == 8 then
            s.li = s.li + e.dir * 8
            if s.li <= e.min then s.li, e.dir = e.min, 1
            elseif s.li >= e.max then s.li, e.dir = e.max, -1 end
        else
            e.timer = e.timer - 1
            if e.timer <= 0 then
                if sp == 1 then
                    e.bright = not e.bright
                    s.li, e.timer = e.bright and e.max or e.min, random(1, 64)
                elseif sp == 17 then
                    e.bright = not e.bright
                    s.li, e.timer = e.bright and e.max or max(0, e.max - 16), 4
                else
                    e.bright = not e.bright
                    s.li = e.bright and e.max or e.min
                    e.timer = e.bright and 5 or ((sp == 2 or sp == 13) and 15 or 35)
                end
            end
        end
    end
end

local function P_CrossSpecialLine(oldX, oldY, newX, newY)
    for _, L in ipairs(lines) do
        if L.sp == 36 or L.sp == 88 then
            local side0 = (L.x2 - L.x1) * (oldY - L.y1) - (L.y2 - L.y1) * (oldX - L.x1)
            local side1 = (L.x2 - L.x1) * (newY - L.y1) - (L.y2 - L.y1) * (newX - L.x1)
            if side0 < 0 and side1 >= 0 then
                local t = side0 / (side0 - side1)
                local hx, hy = oldX + (newX - oldX) * t, oldY + (newY - oldY) * t
                local dx, dy = L.x2 - L.x1, L.y2 - L.y1
                local u = ((hx - L.x1) * dx + (hy - L.y1) * dy) / (dx * dx + dy * dy)
                if u >= 0 and u <= 1 and (L.sp ~= 36 or not L.activated) then
                    if L.sp == 36 then L.activated = true end
                    Mech.startFloorMotion(L)
                end
            end
        end
    end
end

local function useLine()
    local dx, dy = cos(ang), sin(ang)
    local best, bestT, bestIndex
    for i, L in ipairs(lines) do
        if L.sp ~= 0 then
            local ex, ey = L.x2 - L.x1, L.y2 - L.y1
            local denom = dx * ey - dy * ex
            if abs(denom) > 1e-9 then
                local ax, ay = L.x1 - P.x, L.y1 - P.y
                local t = (ax * ey - ay * ex) / denom
                local s = (ax * dy - ay * dx) / denom
                if t > 0 and t < USE_RANGE and s >= 0 and s <= 1 and (not bestT or t < bestT) then
                    best, bestT, bestIndex = L, t, i
                end
            end
        end
    end
    if not best then return end
    local frontSide = (best.x2 - best.x1) * (P.y - best.y1) - (best.y2 - best.y1) * (P.x - best.x1) < 0
    if not frontSide then return end
    if best.sp == 1 or best.sp == 31 then
        Mech.openDoor(best.bs)
    elseif best.sp == 11 then
        for _, s in ipairs(segs) do
            if s.ld == bestIndex then
                for _, key in ipairs({ "mi", "up", "lo" }) do
                    local name = s[key]
                    if name and name:sub(1, 3) == "SW1" then
                        local alternate = "SW2" .. name:sub(4)
                        if texInfo[alternate] then s[key] = alternate end
                    end
                end
            end
        end
        over, exitT, exitTime = "exit", 70, ticCount
        play("DSSWTCHX")
    end
end

-- Bullet puffs, blood and monster drops live in one table to stay under Lua 5.1's 200 locals.
local Fx = {
    puff = { frames = { "PUFFA0", "PUFFB0", "PUFFC0", "PUFFD0" }, tics = 4, bright = true },
    blood = { frames = { "BLUDC0", "BLUDB0", "BLUDA0" }, tics = 8 },
}

function Fx.spawn(kind, x, y, z)
    local sec = sectors[sectorAt(x, y)]
    local fx = Fx[kind]
    local info = sprInfo[fx.frames[1]]
    z = max(sec.fl + 4, min(sec.ce - 4, z))
    actors[#actors + 1] = { fx = fx, x = x, y = y, hz = z, fxT = 0, sprite = fx.frames[1],
        z = info and z - info.to + info.h / 2 or z }
end

function Fx.update(a)
    a.fxT = a.fxT + 1
    local i = floor(a.fxT / a.fx.tics) + 1
    if i > #a.fx.frames then
        a.gone = true
        return
    end
    a.sprite = a.fx.frames[i]
    local info = sprInfo[a.sprite]
    if info then a.z = a.hz - info.to + info.h / 2 end
end

function Fx.drop(a)
    local sprite = a.mon.drop and thingSprite[a.mon.drop]
    if sprite then
        actors[#actors + 1] = { t = a.mon.drop, x = a.x, y = a.y, z = a.z, sprite = sprite, dropped = true }
    end
end

-- sx, sy: where the attack came from, for Doom's knockback (damage / 8 map units per tic).
local function damagePlayer(n, sx, sy)
    if over then return end
    n = floor(n * SKILLS[skill].hurt)
    if sx and (sx ~= P.x or sy ~= P.y) then
        local away = math.atan2 and math.atan2(P.y - sy, P.x - sx) or math.atan(P.y - sy, P.x - sx)
        P.momx, P.momy = P.momx + cos(away) * n / 8, P.momy + sin(away) * n / 8
    end
    if armor > 0 then
        local saved = floor(n / (P.armorType == 2 and 2 or 3))
        if saved >= armor then saved, P.armorType = armor, 0 end
        armor, n = armor - saved, n - saved
    end
    UI.faceHit(n, sx, sy)
    if sx then P.attX, P.attY = sx, sy end
    hp = hp - n
    hurt = min(100, hurt + n) -- Doom's damagecount: the red palette fades as it counts down
    if hp <= 0 then
        hp, over = 0, "dead"
        play("DSPLDETH")
    else
        play("DSPLPAIN")
    end
end

local function hitMonster(a, n)
    local wasAwake = a.awake
    a.hp, a.hit, a.awake = a.hp - n, 3, true
    if not wasAwake and a.hp > 0 then a.state, a.reactionT, a.justWoke = "chase", a.mon.reaction, true end
    if a.hp <= 0 then
        kills = kills + 1
        a.state, a.deathT, a.frame = "death", 0, a.mon.death[1]
        a.attackT, a.attackIndex = nil, nil
        Snd.mon(a, "die")
        Fx.drop(a)
    elseif random(256) <= a.mon.painChance then
        a.state, a.painT = "pain", 3
        a.attackT, a.attackIndex = nil, nil
        Snd.mon(a, "pain")
    end
end

-- Barrel code lives in one table: the main chunk is near Lua 5.1's limit of 200 locals.
local Barrel = { sound = "DSBAREXP" }

function Barrel.damage(a, n)
    if not a.barrel or a.exploding then return end
    a.hp = a.hp - n
    if a.hp <= 0 then
        a.exploding, a.explodeT, a.frame = true, 0, "A"
        for i = #solids, 1, -1 do
            if solids[i] == a then table.remove(solids, i) end
        end
    end
end

-- Doom P_RadiusAttack: box distance minus the target radius, line of sight required.
function Barrel.radiusAttack(x, y, damage)
    for _, t in ipairs(actors) do
        if (t.mon and t.hp > 0) or (t.barrel and not t.exploding) then
            local dist = max(max(abs(t.x - x), abs(t.y - y)) - (t.mon and 20 or 10), 0)
            local dmg = floor(damage - dist)
            if dmg > 0 and hasLOS(x, y, t.x, t.y) then
                if t.mon then hitMonster(t, dmg) else Barrel.damage(t, dmg) end
            end
        end
    end
    local dmg = floor(damage - max(max(abs(P.x - x), abs(P.y - y)) - RADIUS, 0))
    if dmg > 0 and hasLOS(x, y, P.x, P.y) then damagePlayer(dmg, x, y) end
end

function Barrel.update(a)
    if a.exploding then
        a.explodeT = a.explodeT + 1
        local t = a.explodeT
        a.frame = t < 5 and "A" or t < 10 and "B" or t < 15 and "C" or t < 25 and "D" or "E"
        if t == 5 then play(Barrel.sound, a.x, a.y) end
        if t == 15 then Barrel.radiusAttack(a.x, a.y, 128) end
        if t >= 35 then a.gone = true end
    else
        a.animT = a.animT + 1
        a.frame = floor(a.animT / 6) % 2 == 0 and "A" or "B"
    end
end

local function firePellet(spread, range, damage)
    local a = ang + spread
    local dx, dy = cos(a), sin(a)
    local wallT = min(range, rayWall(P.x, P.y, dx, dy))
    local best, bestT
    for _, m in ipairs(actors) do
        if m.mon and m.hp > 0 or m.barrel and not m.exploding then
            local rx, ry = m.x - P.x, m.y - P.y
            local along = rx * dx + ry * dy
            local lateral = abs(rx * dy - ry * dx)
            if along > 0 and along < wallT and lateral < (m.barrel and 12 or 20) and (not bestT or along < bestT) then
                best, bestT = m, along
            end
        end
    end
    if best then
        local hx, hy = P.x + dx * bestT, P.y + dy * bestT
        if best.mon then
            Fx.spawn("blood", hx, hy, viewz)
            hitMonster(best, damage)
        else
            Fx.spawn("puff", hx - dx * 4, hy - dy * 4, viewz)
            Barrel.damage(best, damage)
        end
    elseif wallT < range then
        Fx.spawn("puff", P.x + dx * (wallT - 4), P.y + dy * (wallT - 4), viewz)
    end
    return best ~= nil
end

local function alertNoise()
    local start = sectorAt(P.x, P.y)
    local queue, seen = { { start, 0 } }, { [start] = { true, false } }
    local head = 1
    while head <= #queue do
        local item = queue[head]
        local sec, blocked = item[1], item[2]
        head = head + 1
        for _, L in ipairs(lines) do
            if L.bs > 0 and (L.fs == sec or L.bs == sec) then
                local other = L.fs == sec and L.bs or L.fs
                local F, B = sectors[L.fs], sectors[L.bs]
                local open = min(F.ce, B.ce) - max(F.fl, B.fl)
                local crosses = floor(L.fl / 64) % 2 == 1
                local nextBlocked = blocked or crosses
                if open >= BODY_H and (not crosses or not blocked) then
                    seen[other] = seen[other] or {}
                    local slot = nextBlocked and 2 or 1
                    if not seen[other][slot] then
                        seen[other][slot] = true
                        queue[#queue + 1] = { other, nextBlocked }
                    end
                end
            end
        end
    end
    for _, a in ipairs(actors) do
        if a.mon and not a.awake and not a.ambush and a.hp > 0 and seen[sectorAt(a.x, a.y)] then
            a.awake, a.state, a.reactionT, a.justWoke = true, "chase", a.mon.reaction, true
            Snd.mon(a, "sight")
        end
    end
end

local function spawnFireball(a)
    local dx, dy = P.x - a.x, P.y - a.y
    local d = sqrt(dx * dx + dy * dy)
    if d < 1 then return end
    play("DSFIRSHT", a.x, a.y)
    actors[#actors + 1] = {
        projectile = true, x = a.x, y = a.y, z = a.z + 32,
        vx = dx / d, vy = dy / d, speed = SKILLS[skill].fast and 20 or 10, sprite = "BAL1A0", flightT = 0,
    }
end

-- Attack button for tests and the mouse: starts an attack when the weapon is ready (see WEAPONS.update).
local function fire()
    if over or P.wstate ~= "ready" or P.pending then return end
    WEAPONS.fireWeapon()
end

local PICKUPS = {
    [2007] = function(d) if bullets >= 200 then return false end bullets = min(200, bullets + (d and 5 or 10) * SKILLS[skill].ammo) return "Picked up a clip." end,
    [2048] = function() if bullets >= 200 then return false end bullets = min(200, bullets + 50 * SKILLS[skill].ammo) return "Picked up a box of bullets." end,
    [2008] = function() if shells >= 50 then return false end shells = min(50, shells + 4 * SKILLS[skill].ammo) return "Picked up 4 shotgun shells." end,
    [2049] = function() if shells >= 50 then return false end shells = min(50, shells + 20 * SKILLS[skill].ammo) return "Picked up a box of shotgun shells." end,
    [2011] = function() if hp >= 100 then return false end hp = min(100, hp + 10) return "Picked up a stimpack." end,
    [2012] = function()
        if hp >= 100 then return false end
        local needy = hp < 25
        hp = min(100, hp + 25)
        return needy and "Picked up a medikit that you REALLY need!" or "Picked up a medikit."
    end,
    [2014] = function() if hp >= 200 then return false end hp = min(200, hp + 1) return "Picked up a health bonus." end,
    [2015] = function() if armor >= 200 then return false end armor = min(200, armor + 1) if P.armorType == 0 then P.armorType = 1 end return "Picked up an armor bonus." end,
    [2018] = function() if armor >= 100 then return false end armor, P.armorType = 100, 1 return "Picked up the armor." end,
    [2019] = function() if armor >= 200 then return false end armor, P.armorType = 200, 2 return "Picked up the MegaArmor!" end,
    [2001] = function(d) owned[3] = true shells = min(50, shells + (d and 4 or 8) * SKILLS[skill].ammo) P.pending, P.faceKind, P.faceCount = 3, "grin", 70 return "You got the shotgun!" end,
    [2002] = function(d) owned[4] = true bullets = min(200, bullets + (d and 10 or 20) * SKILLS[skill].ammo) P.pending, P.faceKind, P.faceCount = 4, "grin", 70 return "You got the chaingun!" end,
}

local WALK_FRAMES = { "A", "B", "C", "D" }

local MOVE_DIRS = {
    { 1, 0 }, { 0.7071, 0.7071 }, { 0, 1 }, { -0.7071, 0.7071 },
    { -1, 0 }, { -0.7071, -0.7071 }, { 0, -1 }, { 0.7071, -0.7071 },
}

local function beginMonsterAttack(a)
    a.state, a.attackElapsed, a.attackIndex, a.attackFired = "attack", 0, 1, false
    a.frame = a.mon.attack[1][1]
end

local function monsterHitscan(a, pellets)
    local dx, dy = P.x - a.x, P.y - a.y
    local d = sqrt(dx * dx + dy * dy)
    if d < 1 then return end
    local aim = math.atan2 and math.atan2(dy, dx) or math.atan(dy, dx)
    for _ = 1, pellets do
        -- A_PosAttack/A_SPosAttack: random angle error up to about 22 degrees.
        local angle = aim + (random(0, 255) - random(0, 255)) * (2 * pi / 4096)
        local ux, uy = cos(angle), sin(angle)
        local along = dx * ux + dy * uy
        local lateral = abs(dx * uy - dy * ux)
        if along > 0 and along < rayWall(a.x, a.y, ux, uy) and lateral < RADIUS then
            damagePlayer(3 * random(1, 5), a.x, a.y)
        end
    end
    play(pellets > 1 and "DSSHOTGN" or "DSPISTOL", a.x, a.y)
end

local function explodeProjectile(a)
    a.state, a.explodeT, a.sprite = "explode", 0, "BAL1C0"
    play("DSFIRXPL", a.x, a.y)
end

local function updateProjectiles()
    for _, a in ipairs(actors) do
        if a.projectile and not a.gone then
            if a.state == "explode" then
                a.explodeT = a.explodeT + 1
                if a.explodeT >= 18 then
                    a.gone = true
                else
                    a.sprite = "BAL1" .. (a.explodeT < 6 and "C0" or (a.explodeT < 12 and "D0" or "E0"))
                end
            else
                local oldX, oldY = a.x, a.y
                local dx, dy = a.vx * a.speed, a.vy * a.speed
                local wallT = rayWall(oldX, oldY, a.vx, a.vy)
                local along = (P.x - oldX) * a.vx + (P.y - oldY) * a.vy
                local lateral = abs((P.x - oldX) * a.vy - (P.y - oldY) * a.vx)
                local playerHit = along >= 0 and along <= a.speed and along < wallT and lateral <= 22
                local barrel, barrelAlong
                for _, b in ipairs(actors) do
                    if b.barrel and not b.exploding then
                        local bAlong = (b.x - oldX) * a.vx + (b.y - oldY) * a.vy
                        local bLateral = abs((b.x - oldX) * a.vy - (b.y - oldY) * a.vx)
                        if bAlong >= 0 and bAlong <= a.speed and bAlong < wallT and bLateral <= 16
                            and (not barrelAlong or bAlong < barrelAlong) then
                            barrel, barrelAlong = b, bAlong
                        end
                    end
                end
                if barrel and (not playerHit or barrelAlong < along) then
                    a.x, a.y = oldX + a.vx * barrelAlong, oldY + a.vy * barrelAlong
                    Barrel.damage(barrel, 3 * random(1, 8))
                    explodeProjectile(a)
                elseif playerHit then
                    a.x, a.y = oldX + a.vx * along, oldY + a.vy * along
                    damagePlayer(3 * random(1, 8), a.x, a.y)
                    explodeProjectile(a)
                elseif wallT <= a.speed then
                    a.x, a.y = oldX + a.vx * wallT, oldY + a.vy * wallT
                    explodeProjectile(a)
                else
                    a.x, a.y = oldX + dx, oldY + dy
                    a.flightT = a.flightT + 1
                    a.sprite = a.flightT % 2 == 0 and "BAL1A0" or "BAL1B0"
                end
            end
        end
    end
end

local function updateMonsterAttack(a)
    a.attackElapsed = a.attackElapsed + 1
    local elapsed, index = a.attackElapsed, 1
    while index <= #a.mon.attack and elapsed >= a.mon.attack[index][2] do
        elapsed = elapsed - a.mon.attack[index][2]
        index = index + 1
    end
    if index > #a.mon.attack then
        a.state, a.attackElapsed, a.attackIndex = "chase", nil, nil
        a.cd = 0
        return
    end
    a.attackIndex, a.frame = index, a.mon.attack[index][1]
    if index == 2 and not a.attackFired then
        a.attackFired = true
        local dx, dy = P.x - a.x, P.y - a.y
        local d = sqrt(dx * dx + dy * dy)
        if a.t == 3001 then
            if d <= 64 then
                play("DSCLAW", a.x, a.y)
                if hasLOS(a.x, a.y, P.x, P.y) then damagePlayer(3 * random(1, 8), a.x, a.y) end
            else
                spawnFireball(a)
            end
        else
            monsterHitscan(a, a.t == 9 and 3 or 1)
        end
    end
end

local function canMonsterStep(a, x, y, floorNow)
    local px, py = P.x - x, P.y - y
    if px * px + py * py < (20 + RADIUS) * (20 + RADIUS) then return false end
    return canMove(x, y, floorNow, 20) and not blockedBySolid(x, y, 20, a)
end

local function moveMonster(a, dx, dy, d)
    local desired = floor((math.atan2 and math.atan2(dy, dx) or math.atan(dy, dx)) / (pi / 4) + 0.5) % 8 + 1
    if a.moveCount <= 0 or random(256) == 1 then
        a.moveDir, a.moveCount = desired, random(0, 15)
    end
    local dir = MOVE_DIRS[a.moveDir]
    local floorNow = sectors[sectorAt(a.x, a.y)].fl
    local nx, ny = a.x + dir[1] * a.mon.speed, a.y + dir[2] * a.mon.speed
    if not canMonsterStep(a, nx, ny, floorNow) then
        Mech.monsterUse(a, nx, ny)
        local moved = false
        for offset = 1, 7 do
            local candidate = (desired + offset - 1) % 8 + 1
            local v = MOVE_DIRS[candidate]
            nx, ny = a.x + v[1] * a.mon.speed, a.y + v[2] * a.mon.speed
            if canMonsterStep(a, nx, ny, floorNow) then
                a.moveDir, moved = candidate, true
                break
            end
        end
        if not moved then a.moveCount = 0 return false end
    end
    a.x, a.y = nx, ny
    a.z = sectors[sectorAt(a.x, a.y)].fl
    a.moveCount = a.moveCount - 1
    a.walkT = a.walkT + 1
    a.frame = WALK_FRAMES[a.walkT % #WALK_FRAMES + 1]
    return true
end

local function updateActors()
    for _, a in ipairs(actors) do
        if a.hit and a.hit > 0 then a.hit = a.hit - 1 end
        if a.barrel then
            Barrel.update(a)
        elseif a.fx then
            Fx.update(a)
        elseif a.mon then
            local justWoke = a.justWoke
            a.justWoke = nil
            if a.state == "death" then
                a.deathT = a.deathT + 1
                a.frame = a.mon.death[min(#a.mon.death, floor(a.deathT / 5) + 1)]
            elseif a.state == "pain" then
                a.frame, a.painT = a.mon.prefix == "TROO" and "H" or "G", a.painT - 1
                if a.painT <= 0 then a.state = "chase" end
            elseif a.state == "attack" then
                updateMonsterAttack(a)
            elseif a.hp > 0 then
                local dx, dy = P.x - a.x, P.y - a.y
                local d = sqrt(dx * dx + dy * dy)
                local los = d < 2000 and hasLOS(a.x, a.y, P.x, P.y)
                if not a.awake then
                    a.look = a.look + 1
                    local facing = math.atan2 and math.atan2(dy, dx) or math.atan(dy, dx)
                    local delta = abs((facing - a.facing + pi) % (2 * pi) - pi)
                    if a.look >= 4 then
                        a.look = 0
                        if los and (d <= 128 or delta <= pi / 2) then
                            a.awake, a.state, a.reactionT = true, "chase", a.mon.reaction
                            justWoke = true
                            Snd.mon(a, "sight")
                        end
                    end
                end
                if a.awake and a.state == "chase" then
                    if a.cd > 0 then a.cd = a.cd - 1 end
                    a.chaseT = (a.chaseT or 0) - 1
                    local step = a.chaseT <= 0 -- A_Chase runs once per walk state, not every tic
                    if step then a.chaseT = a.mon.chaseTics end
                    if step and random(0, 255) < 3 then Snd.mon(a, "active") end
                    if step and a.reactionT > 0 and not justWoke then a.reactionT = a.reactionT - 1 end
                    local facing = math.atan2 and math.atan2(dy, dx) or math.atan(dy, dx)
                    if d > 0 then a.facing = facing end
                    local melee = a.mon.melee and d <= 60
                    if step and los and melee then
                        beginMonsterAttack(a)
                    elseif step and a.reactionT <= 0 and los and (a.moveCount <= 0 or SKILLS[skill].fast) then
                        -- P_CheckMissileRange: far targets are attacked less often, and monsters without a melee attack shoot from nearer.
                        local dist = min(d - 64 - (a.mon.melee and 0 or 128), 200)
                        if random(0, 255) >= dist then beginMonsterAttack(a) end
                    end
                    if a.state == "chase" and step then
                        if d > 0 then moveMonster(a, dx, dy, d) else a.frame = "A" end
                    end
                end
            end
        elseif not a.projectile and not a.gone and not a.r then
            local dx, dy = P.x - a.x, P.y - a.y
            if dx * dx + dy * dy < 900 then
                local pick = PICKUPS[a.t]
                if pick then
                    local what = pick(a.dropped)
                    if what then
                        a.gone = true
                        if not a.dropped then itemsFound = itemsFound + 1 end
                        setMessage(what)
                        play((a.t == 2001 or a.t == 2002) and "DSWPNUP" or "DSITEMUP")
                        P.bonus = P.bonus + 6 -- BONUSADD: the yellow pickup flash
                    end
                end
            end
        end
    end
    for i = #actors, 1, -1 do
        if actors[i].fx and actors[i].gone then table.remove(actors, i) end
    end
    local sec = sectors[sectorAt(P.x, P.y)]
    if sec.sp == 7 or sec.sp == 5 or sec.sp == 16 or sec.sp == 4 then
        nukeT = nukeT + 1
        if nukeT >= 32 then
            nukeT = 0
            damagePlayer(sec.sp == 7 and 5 or (sec.sp == 5 and 10 or 20))
        end
    else
        nukeT = 0
    end
end

local function updateSecrets()
    local sec = sectorAt(P.x, P.y)
    if sectors[sec].sp == 9 and not secretSeen[sec] then
        secretSeen[sec] = true
        secretsFound = secretsFound + 1
        setMessage("A secret is revealed!")
    end
end

local function updatePlayer()
    local running = keys.SHIFT or keys.LSHIFT
    local turn = ((keys.LEFT or keys.Q) and 1 or 0) - ((keys.RIGHT or keys.E) and 1 or 0)
    if turn ~= 0 then
        P.turnheld = P.turnheld + 1
        local angleturn = P.turnheld <= 6 and 640 or 1280
        if running then angleturn = angleturn * 2 end
        ang = ang + turn * angleturn * (2 * pi / 65536)
    else
        P.turnheld = 0
    end
    ang = ang % (2 * pi)
    P.angle = floor(ang * BAM / (2 * pi)) % BAM

    local fwd = ((keys.W or keys.UP) and 1 or 0) - ((keys.S or keys.DOWN) and 1 or 0)
    local str = (keys.D and 1 or 0) - (keys.A and 1 or 0)
    local moveScale = running and 2 or 1
    local forwardmove = fwd * 25 * moveScale
    local sidemove = str * (running and 40 or 24)
    local thrust = 2048 / 65536
    local dirx, diry = cos(ang), sin(ang)
    local sideX, sideY = cos(ang - pi / 2), sin(ang - pi / 2)
    P.momx = P.momx + (forwardmove * dirx + sidemove * sideX) * thrust
    P.momy = P.momy + (forwardmove * diry + sidemove * sideY) * thrust
    P.momx, P.momy = max(-MAXMOVE, min(MAXMOVE, P.momx)), max(-MAXMOVE, min(MAXMOVE, P.momy))

    local function canOccupy(x, y, fromFloor)
        local nextFloor = sectors[sectorAt(x, y)].fl
        if nextFloor - fromFloor > STEP_H then return false, nextFloor end
        if not canMove(x, y, fromFloor, RADIUS) or blockedBySolid(x, y, RADIUS, P) then
            return false, nextFloor
        end
        return true, nextFloor
    end

    local currentFloor = sectors[sectorAt(P.x, P.y)].fl
    floorZ, P.floorZ = currentFloor, currentFloor
    local steps = max(abs(P.momx), abs(P.momy)) > MAXMOVE / 2 and 2 or 1
    local dx, dy = P.momx / steps, P.momy / steps
    for _ = 1, steps do
        local moved, nextFloor = canOccupy(P.x + dx, P.y + dy, floorZ)
        if moved then
            P.x, P.y = P.x + dx, P.y + dy
        else
            local movedX, floorX = canOccupy(P.x + dx, P.y, floorZ)
            if movedX then P.x = P.x + dx else P.momx = 0 end
            local movedY, floorY = canOccupy(P.x, P.y + dy, floorZ)
            if movedY then P.y = P.y + dy else P.momy = 0 end
            nextFloor = movedY and floorY or (movedX and floorX or floorZ)
        end
        if nextFloor > floorZ then
            P.viewheight = max(20, P.viewheight - (nextFloor - floorZ))
            P.deltaviewheight = max(1, (EYE - P.viewheight) / 4)
        end
        floorZ, P.floorZ = sectors[sectorAt(P.x, P.y)].fl, sectors[sectorAt(P.x, P.y)].fl
    end
    if fwd == 0 and str == 0 and P.momx * P.momx + P.momy * P.momy < STOPSPEED * STOPSPEED then
        P.momx, P.momy = 0, 0
    else
        P.momx, P.momy = P.momx * FRICTION, P.momy * FRICTION
    end
    if P.viewheight < EYE then
        P.deltaviewheight = max(1, (EYE - P.viewheight) / 4)
        P.viewheight = min(EYE, P.viewheight + P.deltaviewheight)
    else
        P.viewheight, P.deltaviewheight = EYE, 0
    end
    P.bob = min(16, (P.momx * P.momx + P.momy * P.momy) / 4) -- MAXBOB is 16 units
    P.viewbob = sin(ticCount * (2 * pi / 20)) * P.bob / 2
    viewz = floorZ + P.viewheight + P.viewbob
end

-- Weapon sprite logic like Doom's p_pspr.c: states with tic counts and actions, run once per tic.
function WEAPONS.ammoOk()
    local w = WEAPONS[weapon]
    if not w.ammo or (w.ammo == "bullets" and bullets or shells) > 0 then return true end
    -- Out of ammo: switch to the best weapon that still has some.
    if owned[4] and bullets > 0 then P.pending = 4
    elseif owned[3] and shells > 0 then P.pending = 3
    elseif bullets > 0 then P.pending = 2
    else P.pending = 1 end
    if P.pending == weapon then P.pending = nil end
    return false
end

function WEAPONS.fireWeapon()
    if WEAPONS.ammoOk() then
        alertNoise()
        WEAPONS.enter(1)
    end
end

-- A_FirePistol, A_FireShotgun, A_FireCGun and A_Punch.
function WEAPONS.shoot(w, shot)
    local scatter = (2 * pi / 16384)
    if w.melee then
        if firePellet((random(0, 255) - random(0, 255)) * scatter, 64, 2 * random(1, 10)) then play(w.sound) end
        return
    end
    if (w.ammo == "bullets" and bullets or shells) <= 0 then return end
    play(w.sound)
    if w.ammo == "bullets" then bullets = bullets - 1 else shells = shells - 1 end
    local seq = w.flash[shot or 1]
    P.fseq, P.fi, P.ftics, Light.extra = seq, 1, seq[1][2], seq[1][3]
    for _ = 1, w.pellets do
        -- P_GunShot: shotgun pellets and refired shots stray up to about 5.6 degrees.
        local spread = 0
        if w.pellets > 1 or P.refire > 0 then spread = (random(0, 255) - random(0, 255)) * scatter end
        firePellet(spread, 2048, 5 * random(1, 3))
    end
end

-- Enters attack state i and runs its action; zero-tic states fall through in the same tic.
function WEAPONS.enter(i)
    local w = WEAPONS[weapon]
    P.wstate = "attack"
    while true do
        local st = w.attack[i]
        if not st then
            P.wstate, P.wi = "ready", nil
            WEAPONS.ready()
            return
        end
        P.wi, P.wtics = i, st[2]
        local restart = false
        if st[3] == "fire" then
            WEAPONS.shoot(w, st[4])
        elseif st[3] == "refire" then -- A_ReFire
            if keys.SPACE and not P.pending and hp > 0 then
                P.refire = P.refire + 1
                if WEAPONS.ammoOk() then
                    alertNoise()
                    restart = true
                end
            else
                P.refire = 0
                WEAPONS.ammoOk()
            end
        end
        if restart then i = 1
        elseif P.wtics > 0 then return
        else i = i + 1 end
    end
end

-- A_WeaponReady: start lowering for a pending switch or death, fire on the attack button, else bob.
function WEAPONS.ready()
    if P.pending == weapon then P.pending = nil end
    if P.pending or hp <= 0 then
        P.wstate = "lower"
        WEAPONS.lower()
        return
    end
    if keys.SPACE and not over then
        WEAPONS.fireWeapon()
        if P.wstate == "attack" then return end
    end
    local th = (ticCount % 64) * (2 * pi / 64)
    P.wsx = 1 + P.bob * cos(th)
    P.wsy = 32 + P.bob * sin(th % pi)
    P.wy = P.wsy - 32
end

-- A_Lower and A_Raise move the weapon 6 pixels per tic between y 32 and 128.
function WEAPONS.lower()
    P.wsy = P.wsy + 6
    if P.wsy < 128 then
        P.wy = P.wsy - 32
        return
    end
    P.wsy, P.wy = 128, 96
    if hp <= 0 then return end
    weapon, P.pending = P.pending or weapon, nil
    P.wstate = "raise"
    WEAPONS.raise()
end

function WEAPONS.raise()
    P.wsy = P.wsy - 6
    if P.wsy > 32 then
        P.wy = P.wsy - 32
        return
    end
    P.wsy, P.wy, P.wstate = 32, 0, "ready"
    WEAPONS.ready()
end

function WEAPONS.update()
    if P.wstate == "attack" then
        P.wtics = P.wtics - 1
        if P.wtics <= 0 then WEAPONS.enter(P.wi + 1) end
    elseif P.wstate == "ready" then
        WEAPONS.ready()
    elseif P.wstate == "lower" then
        WEAPONS.lower()
    else
        WEAPONS.raise()
    end
    if P.fseq then -- the muzzle flash sprite and its extra light
        P.ftics = P.ftics - 1
        if P.ftics <= 0 then
            P.fi = P.fi + 1
            local st = P.fseq[P.fi]
            if st then
                P.ftics, Light.extra = st[2], st[3]
            else
                P.fseq, Light.extra = nil, 0
            end
        end
    end
end

local function tick()
    ticCount = ticCount + 1
    gameTime = ticCount * TIC_TIME
    hurt = max(0, hurt - 1)
    P.bonus = max(0, P.bonus - 1)
    msgT = max(0, msgT - 1)
    faceT = faceT - 1
    if faceT <= 0 then faceT, faceFrame = 17, random(0, 2) end
    UI.faceTick()
    Mech.updateDoors()
    Mech.updateLightEffects()
    Mech.updateFloorMovers()
    if over then
        if over == "exit" then
            exitT = exitT - 1
            if exitT <= 0 then over = "complete" end
        end
        if over == "dead" then UI.deathTic() end
        return
    end
    local oldX, oldY = P.x, P.y
    updatePlayer()
    WEAPONS.update()
    P_CrossSpecialLine(oldX, oldY, P.x, P.y)
    updateSecrets()
    updateProjectiles()
    updateActors()
end

local function update(dt)
    if UI.paused then return end
    updateAccumulator = updateAccumulator + max(0, dt or 0)
    local count = 0
    while updateAccumulator >= TIC_TIME and count < 5 do
        updateAccumulator = updateAccumulator - TIC_TIME
        tick()
        count = count + 1
    end
end

-- Doom's ST_doPaletteStuff: red palettes 2-8 by damage taken, yellow 10-12 after a pickup.
function UI.flash()
    local p = 0
    if hurt > 0 then p = 1 + min(7, floor((hurt + 7) / 8))
    elseif P.bonus > 0 then p = 9 + min(3, floor((P.bonus + 7) / 8)) end
    return assets.palfx[p]
end

-- P_DeathThink: the view sinks to the floor, the weapon drops, and the player turns toward the killer.
function UI.deathTic()
    WEAPONS.update()
    P.viewheight = max(6, P.viewheight - 1)
    viewz = floorZ + P.viewheight
    if P.attX then
        local want = math.atan2 and math.atan2(P.attY - P.y, P.attX - P.x) or math.atan(P.attY - P.y, P.attX - P.x)
        local diff = (want - ang + pi) % (2 * pi) - pi
        local step = 5 * pi / 180
        ang = abs(diff) < step and want or ang + (diff > 0 and step or -step)
        ang = ang % (2 * pi)
        P.angle = floor(ang * BAM / (2 * pi)) % BAM
    end
end

local function updateText()
    local fx = UI.flash()
    if fx then
        hurtTex:SetColorTexture(fx[1], fx[2], fx[3], 1)
        hurtTex:SetAlpha(fx[4])
    else
        hurtTex:SetAlpha(0)
    end
end

view:SetScript("OnUpdate", function(_, elapsed)
    Snd.sync()
    if UI.screen ~= "game" then
        UI.update(elapsed)
        return
    end
    update(elapsed)
    if over == "complete" then
        UI.beginInter()
        return
    end
    render()
    updateText()
end)

view:SetScript("OnKeyDown", function(self, key)
    self:SetPropagateKeyboardInput(false)
    if UI.screen ~= "game" then
        UI.key(self, key)
    elseif key == "ESCAPE" then
        wipe(keys)
        UI.stack, UI.screen, UI.item, UI.back = {}, "menu", 1, "game" -- Doom's menu pauses the game
        play("DSSWTCHN")
    elseif key == "R" and over then
        reset()
    elseif key == "P" then
        UI.paused = not UI.paused
    elseif key == "F" and over == "dead" then
        reset() -- like Doom, Use respawns you
    elseif key == "F" then
        useLine()
    elseif tonumber(key) and WEAPONS[tonumber(key)] and owned[tonumber(key)] then
        if tonumber(key) ~= weapon then P.pending = tonumber(key) end
    else
        keys[key] = true
    end
end)
view:SetScript("OnKeyUp", function(_, key) keys[key] = nil end)
view:SetScript("OnMouseDown", function()
    if UI.screen == "game" then keys.SPACE = true else UI.key(view, "ENTER") end
end)
view:SetScript("OnMouseUp", function() keys.SPACE = nil end)
view:SetScript("OnShow", function() wipe(keys) end)
view:SetScript("OnHide", function()
    wipe(keys)
    Snd.stop()
end)

reset()

local function countLevelTotals()
    killsTotal, itemsTotal, secretsTotal = 0, 0, 0
    for _, a in ipairs(actors) do
        if a.mon then killsTotal = killsTotal + 1
        elseif PICKUPS[a.t] then itemsTotal = itemsTotal + 1 end
    end
    for _, s in ipairs(sectors) do
        if s.sp == 9 then secretsTotal = secretsTotal + 1 end
    end
end

countLevelTotals()

-- Title, menus and intermission screens -----------------------------------------------------------
function UI.start(n)
    skill = n
    reset()
    countLevelTotals()
    UI.screen, UI.back, UI.stack = "game", "game", {}
end

function UI.beginInter()
    UI.kp = killsTotal > 0 and floor(kills * 100 / killsTotal) or 100
    UI.ip = itemsTotal > 0 and floor(itemsFound * 100 / itemsTotal) or 100
    UI.sp = secretsTotal > 0 and floor(secretsFound * 100 / secretsTotal) or 100
    UI.seconds = floor((exitTime or ticCount) / TIC_RATE)
    UI.cnt = { k = 0, i = 0, s = 0, time = 0, par = 0 }
    UI.phase, UI.pause, UI.t, UI.screen = 1, TIC_RATE, 0, "inter"
end

function UI.finishCounts()
    UI.cnt = { k = UI.kp, i = UI.ip, s = UI.sp, time = UI.seconds, par = UI.par }
    UI.phase = 5
    play(Barrel.sound)
end

-- Doom's WI_updateStats: count each stat up, pausing a second between them.
function UI.interTic()
    if UI.phase >= 5 then return end
    if UI.pause > 0 then
        UI.pause = UI.pause - 1
        return
    end
    local c, phase = UI.cnt, UI.phase
    if UI.t % 4 == 0 then play("DSPISTOL") end
    if phase == 1 then
        c.k = min(UI.kp, c.k + 2)
        if c.k >= UI.kp then UI.phase, UI.pause = 2, TIC_RATE; play(Barrel.sound) end
    elseif phase == 2 then
        c.i = min(UI.ip, c.i + 2)
        if c.i >= UI.ip then UI.phase, UI.pause = 3, TIC_RATE; play(Barrel.sound) end
    elseif phase == 3 then
        c.s = min(UI.sp, c.s + 2)
        if c.s >= UI.sp then UI.phase, UI.pause = 4, TIC_RATE; play(Barrel.sound) end
    else
        c.time, c.par = min(UI.seconds, c.time + 3), min(UI.par, c.par + 3)
        if c.time >= UI.seconds then
            c.par, UI.phase = UI.par, 5
            play(Barrel.sound)
        end
    end
end

-- Doom's menus (m_menu.c): screens stack, so Escape returns to the previous one.
UI.MAIN = { "M_NGAME", "M_OPTION", "M_LOADG", "M_SAVEG", "M_RDTHIS", "M_QUITG" }
UI.EPIS = { "M_EPI1", "M_EPI2", "M_EPI3" }
UI.OPTROWS = { 1, 2, 3, 4, 6, 8 } -- the selectable rows of the options menu; the others hold slider bars
UI.OPTNAMES = { "M_ENDGAM", "M_MESSG", "M_DETAIL", "M_SCRNSZ", false, "M_MSENS", false, "M_SVOL" }
UI.TEXT = {
    shareware = "THIS IS THE SHAREWARE VERSION OF DOOM.\n\nYOU NEED TO ORDER THE ENTIRE TRILOGY.\n\nPRESS A KEY.",
    nightmare = "ARE YOU SURE? THIS SKILL LEVEL\nISN'T EVEN REMOTELY FAIR.\n\nPRESS Y OR N.",
    quit = "ARE YOU SURE YOU WANT TO\nQUIT THIS GREAT GAME?\n\n(PRESS Y TO QUIT)",
    endgame = "ARE YOU SURE YOU WANT TO END THE GAME?\n\nPRESS Y OR N.",
    save = "SAVING AND LOADING GAMES IS\nNOT AVAILABLE IN THIS VERSION.\n\nPRESS A KEY.",
}

function UI.go(screen, item)
    UI.stack[#UI.stack + 1] = { UI.screen, UI.item }
    UI.screen, UI.item = screen, item or 1
end

function UI.pop()
    local prev = table.remove(UI.stack)
    if prev then
        UI.screen, UI.item = prev[1], prev[2]
    else
        UI.screen, UI.item = UI.back == "game" and "game" or "title", 1
    end
end

-- A message box; `yes` runs when Y is pressed, and without it any key just closes the box.
function UI.ask(text, yes)
    UI.boxText, UI.boxYes = text, yes
    UI.go("msg")
end

function UI.choose(window, key)
    local s, item = UI.screen, UI.item
    local ok = key ~= "LEFT" and key ~= "RIGHT"
    play(s == "options" and "DSSTNMOV" or "DSPISTOL")
    if s == "menu" and ok then
        if item == 1 then UI.go("episode", 1)
        elseif item == 2 then UI.go("options", 1)
        elseif item == 5 then UI.go("help")
        elseif item == 6 then UI.ask(UI.TEXT.quit, function(w) w:Hide() end)
        else UI.ask(UI.TEXT.save) end
    elseif s == "episode" and ok then
        if item == 1 then UI.go("skill", 3) else UI.ask(UI.TEXT.shareware) end
    elseif s == "skill" and ok then
        if item == 5 then UI.ask(UI.TEXT.nightmare, function() UI.start(5) end) else UI.start(item) end
    elseif s == "options" then
        local row = UI.OPTROWS[item]
        if row == 1 and ok then
            if UI.back == "game" then
                UI.ask(UI.TEXT.endgame, function() UI.back, UI.screen, UI.stack = "title", "title", {} end)
            end
        elseif row == 2 then
            UI.showMessages = not UI.showMessages
            setMessage(UI.showMessages and "Messages ON" or "Messages OFF")
        elseif row == 3 then
            Light.apply(Light.presets[COLS == 320 and "fast" or "hi"])
        end
    end
end

function UI.key(window, key)
    local s = UI.screen
    local up, down = key == "UP" or key == "W", key == "DOWN" or key == "S"
    if s == "title" then
        if key == "ESCAPE" then window:Hide() else UI.go("menu", 1); play("DSSWTCHN") end
    elseif s == "inter" then
        if UI.phase < 5 then UI.finishCounts() else UI.screen, UI.back, UI.t = "title", "title", 0 end
    elseif s == "msg" then
        local yes = UI.boxYes
        if not yes or key == "Y" or key == "N" or key == "ESCAPE" or key == "SPACE" then
            UI.pop()
            play("DSSWTCHX")
            if yes and key == "Y" then yes(window) end
        end
    elseif s == "help" then
        UI.pop()
        play("DSSWTCHX")
    else
        local count = ({ menu = #UI.MAIN, episode = #UI.EPIS, skill = #SKILLS, options = #UI.OPTROWS })[s]
        if key == "ESCAPE" or key == "BACKSPACE" then
            UI.pop()
            play("DSSWTCHX")
        elseif up then
            UI.item = (UI.item - 2) % count + 1
            play("DSPSTOP")
        elseif down then
            UI.item = UI.item % count + 1
            play("DSPSTOP")
        elseif key == "ENTER" or key == "NUMPADENTER" or key == "SPACE" or key == "LEFT" or key == "RIGHT" then
            UI.choose(window, key)
        end
    end
end

-- Right-aligned number in Doom's intermission font; returns the left edge.
function UI.num(value, x, y, digits)
    local s = tostring(floor(value))
    if digits and #s < digits then s = string.rep("0", digits - #s) .. s end
    local w = sprInfo.WINUM0.w
    for i = #s, 1, -1 do
        x = x - w
        drawPatch("WINUM" .. s:sub(i, i), x, y, "OVERLAY", 1)
    end
    return x
end

-- Doom's status-bar face: a special face after a hit, weapon pickup or long firing, else a random glance.
function UI.faceHit(n, sx, sy)
    if over then return end
    if n > 20 then
        P.faceKind, P.faceCount = "ouch", 35
    elseif sx then
        local toward = math.atan2 and math.atan2(sy - P.y, sx - P.x) or math.atan(sy - P.y, sx - P.x)
        local diff = (toward - ang + pi) % (2 * pi) - pi
        if abs(diff) < pi / 4 then P.faceKind = "rampage" elseif diff > 0 then P.faceKind = "turnL" else P.faceKind = "turnR" end
        P.faceCount = 35
    else
        P.faceKind, P.faceCount = "rampage", 1
    end
end

function UI.faceTick()
    if P.faceCount > 0 then P.faceCount = P.faceCount - 1 end
    P.attackDown = (keys.SPACE and not over) and P.attackDown + 1 or 0
end

function UI.face()
    if hp <= 0 then return "STFDEAD0" end
    local pl = floor((100 - min(hp, 100)) * 5 / 101)
    local kind = P.faceCount > 0 and P.faceKind or (P.attackDown >= 70 and "rampage") or nil
    if kind == "ouch" then return "STFOUCH" .. pl end
    if kind == "rampage" then return "STFKILL" .. pl end
    if kind == "grin" then return "STFEVL" .. pl end
    if kind == "turnL" then return "STFTL" .. pl .. "0" end
    if kind == "turnR" then return "STFTR" .. pl .. "0" end
    return "STFST" .. pl .. faceFrame
end

-- Doom's heads-up font (STCFN033-095): uppercase only, patch widths as advance, 4 pixels for anything else.
function UI.hu(text, x, y, sub)
    text = text:upper()
    for i = 1, #text do
        local b = text:byte(i)
        local name = b >= 33 and b <= 95 and string.format("STCFN%03d", b)
        local info = name and sprInfo[name]
        if info then
            if x + info.w > SW then return end
            drawPatch(name, x, y, "OVERLAY", sub or 3)
            x = x + info.w
        else
            x = x + 4
        end
    end
end

function UI.huWidth(text)
    local w = 0
    for i = 1, #text do
        local b = text:byte(i)
        local info = b >= 33 and b <= 95 and sprInfo[string.format("STCFN%03d", b)]
        w = w + (info and info.w or 4)
    end
    return w
end

function UI.thermo(x, y, width, dot)
    drawPatch("M_THERML", x, y, "OVERLAY", 5)
    for i = 1, width do drawPatch("M_THERMM", x + 8 * i, y, "OVERLAY", 5) end
    drawPatch("M_THERMR", x + 8 * (width + 1), y, "OVERLAY", 5)
    drawPatch("M_THERMO", x + 8 + dot * 8, y, "OVERLAY", 6)
end

-- Menu screens drawn over the title picture or the paused game (sublevels 5 and 6 sit above the HUD).
function UI.drawMenu()
    local s = UI.screen
    local skull = floor(UI.t / 8) % 2 == 0 and "M_SKULL1" or "M_SKULL2"
    if s == "menu" then
        drawPatch("M_DOOM", 94, 2, "OVERLAY", 5)
        for i, name in ipairs(UI.MAIN) do drawPatch(name, 97, 64 + 16 * (i - 1), "OVERLAY", 5) end
        drawPatch(skull, 65, 59 + 16 * (UI.item - 1), "OVERLAY", 6)
    elseif s == "episode" then
        drawPatch("M_EPISOD", 54, 38, "OVERLAY", 5)
        for i, name in ipairs(UI.EPIS) do drawPatch(name, 48, 63 + 16 * (i - 1), "OVERLAY", 5) end
        drawPatch(skull, 16, 58 + 16 * (UI.item - 1), "OVERLAY", 6)
    elseif s == "skill" then
        drawPatch("M_NEWG", 96, 14, "OVERLAY", 5)
        drawPatch("M_SKILL", 54, 38, "OVERLAY", 5)
        for i, sk in ipairs(SKILLS) do drawPatch(sk.lump, 48, 63 + 16 * (i - 1), "OVERLAY", 5) end
        drawPatch(skull, 16, 58 + 16 * (UI.item - 1), "OVERLAY", 6)
    elseif s == "options" then
        drawPatch("M_OPTTTL", 108, 15, "OVERLAY", 5)
        for row, name in ipairs(UI.OPTNAMES) do
            if name then drawPatch(name, 60, 37 + 16 * (row - 1), "OVERLAY", 5) end
        end
        drawPatch(UI.showMessages and "M_MSGON" or "M_MSGOFF", 180, 53, "OVERLAY", 5)
        drawPatch(COLS == 320 and "M_GDHIGH" or "M_GDLOW", 235, 69, "OVERLAY", 5)
        UI.thermo(60, 101, 9, 7)
        UI.thermo(60, 133, 10, 5)
        UI.thermo(60, 165, 16, 8)
        drawPatch(skull, 28, 32 + 16 * (UI.OPTROWS[UI.item] - 1), "OVERLAY", 6)
    elseif s == "help" then
        drawPatch("HELP1", 0, 0, "OVERLAY", 5)
    elseif s == "msg" then
        local lines = {}
        for line in (UI.boxText .. "\n"):gmatch("(.-)\n") do lines[#lines + 1] = line end
        local y = 100 - floor(7 * #lines / 2)
        for i, line in ipairs(lines) do
            UI.hu(line, (SW - UI.huWidth(line)) / 2, y + 12 * (i - 1), 6)
        end
    end
end

-- Small yellow number (status bar ammo table), right-aligned.
function UI.small(value, x, y)
    local s = tostring(floor(value))
    for i = #s, 1, -1 do
        x = x - 4
        drawPatch("STYSNUM" .. s:sub(i, i), x, y, "OVERLAY", 3)
    end
end

function UI.percent(value, x, y)
    drawPatch("WIPCNT", x, y, "OVERLAY", 1)
    UI.num(value, x, y)
end

function UI.time(seconds, x, y)
    local left = UI.num(seconds % 60, x, y, 2) - sprInfo.WICOLON.w
    drawPatch("WICOLON", left, y, "OVERLAY", 1)
    UI.num(floor(seconds / 60), left, y, 2)
end

function UI.draw()
    hurtTex:SetAlpha(0)
    if UI.screen == "inter" then
        local c, lh = UI.cnt, 3 * sprInfo.WINUM0.h / 2
        drawPatch("WIMAP0", 0, 0, "OVERLAY", 0)
        drawPatch("WILV00", (SW - sprInfo.WILV00.w) / 2, 2, "OVERLAY", 1)
        drawPatch("WIF", (SW - sprInfo.WIF.w) / 2, 2 + 5 * sprInfo.WILV00.h / 4, "OVERLAY", 1)
        drawPatch("WIOSTK", 50, 50, "OVERLAY", 1)
        UI.percent(c.k, SW - 50, 50)
        drawPatch("WIOSTI", 50, 50 + lh, "OVERLAY", 1)
        UI.percent(c.i, SW - 50, 50 + lh)
        drawPatch("WISCRT2", 50, 50 + 2 * lh, "OVERLAY", 1)
        UI.percent(c.s, SW - 50, 50 + 2 * lh)
        drawPatch("WITIME", 16, 168, "OVERLAY", 1)
        UI.time(c.time, SW / 2 - 16, 168)
        drawPatch("WIPAR", SW / 2 + 16, 168, "OVERLAY", 1)
        UI.time(c.par, SW - 16, 168)
    elseif UI.back == "game" then
        render() -- the paused game, with the menu drawn on top by render()
        return
    else
        drawPatch("TITLEPIC", 0, 0, "OVERLAY", 0)
        UI.drawMenu()
    end
    releaseUnused()
end

function UI.update(dt)
    UI.acc = UI.acc + max(0, dt or 0)
    local count = 0
    while UI.acc >= TIC_TIME and count < 5 do
        UI.acc, count = UI.acc - TIC_TIME, count + 1
        UI.t = UI.t + 1
        if UI.screen == "inter" then UI.interTic() end
    end
    UI.draw()
end

ns.ui, ns.getSkill, ns.damagePlayer, ns.fx = UI, function() return skill end, damagePlayer, Fx

ns.view, ns.update, ns.tick, ns.render, ns.state = view, update, tick, render, { P = P, keys = keys, actors = actors }
ns.state.getHP = function() return hp end
ns.state.getAmmo = function() return bullets, shells, armor end
ns.state.getWeapon = function() return weapon end
ns.state.getStats = function()
    return { kills = kills, killsTotal = killsTotal, items = itemsFound, itemsTotal = itemsTotal,
        secrets = secretsFound, secretsTotal = secretsTotal, elapsed = exitTime or ticCount, over = over }
end
ns.state.getMessage = function() return msgText end
ns.useLine, ns.fire, ns.rayWall, ns.hasLOS = useLine, fire, rayWall, hasLOS
ns.sectorAt = sectorAt
ns.crossSpecialLine = P_CrossSpecialLine
function ns.setAngle(a)
    ang = a % (2 * pi)
    P.angle = floor(ang * BAM / (2 * pi)) % BAM
end
ns.Light = Light
ns.Snd = Snd
function ns.setColumns(n)
    if not setColumnCount(n) then return false end
    render()
    return COLS
end
function ns.getColumns() return COLS end

SLASH_WODOOM1 = "/wodoom"
SlashCmdList["WODOOM"] = function(msg)
    local mode = (msg or ""):lower():match("^%s*(.-)%s*$")
    local preset = Light.presets[mode]
    if mode == "sound on" or mode == "sound off" then
        Snd.enabled = mode == "sound on"
    elseif mode == "music on" or mode == "music off" then
        Snd.musicOn = mode == "music on"
        Snd.sync()
    elseif preset then
        Light.apply(preset)
        ns.setColumns(preset.cols)
    else
        view:SetShown(not view:IsShown())
    end
end
